# config.py
import os

# Directory to monitor (ensure this directory exists)
MONITORED_DIRECTORY = os.path.join(os.getcwd(), 'monitored_files')

# Baseline file (will be generated by baseline.py)
BASELINE_FILE = os.path.join(os.getcwd(), 'baseline.json')

# Log file for recording events
LOG_FILE = os.path.join(os.getcwd(), 'fim_report.log')
